packages:
  - 'apps/*'
  - 'infra'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - 'prisma'
  - 'argon2'
  - 'cpu-features'
  - 'esbuild'
  - 'protobufjs'
  - 'ssh2'
