packages:
  - 'apps/*'
  - 'infra'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - 'prisma'
allowBuilds:
  '0': '@'
  '1': n
  '2': e
  '3': s
  '4': t
  '5': j
  '6': s
  '7': /
  '8': c
  '9': o
  '10': r
  '11': e
  '12': ','
  '13': '@'
  '14': p
  '15': r
  '16': i
  '17': s
  '18': m
  '19': a
  '20': /
  '21': c
  '22': l
  '23': i
  '24': e
  '25': n
  '26': t
  '27': ','
  '28': '@'
  '29': p
  '30': r
  '31': i
  '32': s
  '33': m
  '34': a
  '35': /
  '36': e
  '37': n
  '38': g
  '39': i
  '40': n
  '41': e
  '42': s
  '43': ','
  '44': p
  '45': r
  '46': i
  '47': s
  '48': m
  '49': a
  '@nestjs/core': set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  prisma: set this to true or false
  esbuild: set this to true or false
  argon2: set this to true or false
  cpu-features: set this to true or false
  protobufjs: set this to true or false
  ssh2: set this to true or false
