// Generated from apps/web/public/logo.png, downscaled to 64x64 and thresholded to
// 1-bit — the label is thermal, so anti-aliased grey prints as noise. Embedded
// rather than shipped as a file so no build-asset copying is needed.
export const BRAND_MARK_PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAI6SURBVHic5VtbjsMwCMSr3v/K3q9UURTbPIYBqfMZtcGMMZhHxpxzyg/jr3oB1SglYIwhY4zKJdQRcFe8koQPW+BK2es52yXRCNDuMpuIVAJOSl9Kvv3u/iyTjJERBrWKo/4XAYQArXlrRaHft5VlJcDqsaOLzJZ3JMATorLObMZaIE6Q5bGfchD3BxMB3dIGrzO94+dzAdcRQJhexJpW8j3vLM0FPEQilZcOR8BCAlp56UCAKEnIUF66EHBCZroMS4ai19wxxus7dsojwjLdAiyLzlZeqo6AZvEM5aWrD2ApL1UE7BRkKi8VBHg9elYeAosC0VA150yL9Tu08AE7BbMz0HICdoVRRvpdSsBOeRbojRF57Gx1a4x+Fb7jpPzqeoxEuQ84IdtCWhGAqPFZ0YoAKSChHQFCJqElAUIkoS0BQiKh5B5wQRPiVjkCKkQeLaDTpeUJxFyBywJ2mZsG1qxvJy9qCWYfUDXLs5N3rcmzKSoCujRFdxai/e0TrihQZQVvMqMZpdoHRM69dULsLtOzFsvGuO8BlVZwyUXUE0wErCY0Kn2E1mpWMFtAxpiKF1HlBXUVriABJdM9JxgpYkbL38gCqtsCrJ1cFNDV49ARYJOQUToP+wAWCW8ODxF9oIOSbx9BZIzKIsMufFocuWBGt4g6Ls+KEhakEPB9uWMH2T3CVALEsJsVrXFhEPAVtNnZqs6wMAkQ8pcgWlCrwqf0tSKrbDMmV5VSl/UFutQZW3eGGPh5Av4BqQhrbq8sKIYAAAAASUVORK5CYII=',
  'base64',
);
