-- AlterTable
ALTER TABLE `SwapPrinter` ADD COLUMN `marginBottom` INTEGER NOT NULL DEFAULT 8,
    ADD COLUMN `marginLeft` INTEGER NOT NULL DEFAULT 24,
    ADD COLUMN `marginRight` INTEGER NOT NULL DEFAULT 16,
    ADD COLUMN `marginTop` INTEGER NOT NULL DEFAULT 8;
