-- AlterTable
ALTER TABLE `SwapPrinter` MODIFY `marginBottom` INTEGER NOT NULL DEFAULT 4,
    MODIFY `marginLeft` INTEGER NOT NULL DEFAULT 0,
    MODIFY `marginRight` INTEGER NOT NULL DEFAULT 28,
    MODIFY `marginTop` INTEGER NOT NULL DEFAULT 4;
